

// This relates to burstcoin and BHD, which mine by demonstrating storage capacity.
// The network capacity is many orders of magnitude larger than petabytes.
// Meanwhile, other networks like siacoin, have excess capacity.
// Since cryptocurrency is inhibited, for some time there is a space where the capcaity
// of one netowrk could be used to make money on another.
// There are many similar spaces.  This one is near.

#define _FILE_OFFSET_BITS 64
#include <cstdint>

struct nonce
{
	struct scoop {
		uint8_t hash_a[32];
		// in POC2, hash_b is swapped with that of the mirror scoop index2=4095-index1
		uint8_t hash_b[32];
	};
	struct scoop scoops[4096];
};

// each value is a 64-bit number, _not_ zero-prefixed
// POC1 filename: AccountID_StartingNonce_NrOfNonces_Stagger [stagger is nonces per group]
// POC2 filename: AccountID_StartingNonce_NrOfNonces
// 	the data is just a sequence of scoops: all the scoop 0s in nonce order,
// 	  then all scoop 1s in nonce order, etc
//
// For sequential reading, the most optimal way to store a plot file is with an entire
// drive as a single file.

extern "C" {

// from libShabal's autogenerated header file.  some of the file has errors, so just pasted in

/// Creates a single PoC Nonce.
///
/// `plot_buffer` must be correct size - no size checks are performed.
void create_plot(uint64_t account_id,
                 uint64_t nonce,
                 uint8_t poc_version,
                 uint8_t *plot_buffer,
                 uintptr_t plot_buffer_offset);

}

#include <cassert>

#include "skystream.hpp"

/*
class BufferedSkystream : public skystream
{
public:
	BufferedSkystream(sia::portalpool & portalpool)
	:skystream(portalpool) {start();}
	BufferedSkystream(nlohmann::json identifiers, sia::portalpool & portalpool)
	:skystream(identifiers, portalpool) {start();}

	BufferedSkystream(BufferedSkystream const &) = default;
	BufferedSkystream(BufferedSkystream &&) = default;

	~BufferedSkystream()
	{
		shutdown();
	}

	void shutdown()
	{
		{
			std::lock_guard<std::mutex> lock(mutex);
			if (!pumping) {
				return;
			}
			pumping = false;
		}
		threadup.join();
		threaddown.join();
	}

	uint64_t size()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return offsetup;
	}
	uint64_t backlog()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return queueup.size();
	}
	uint64_t uploadedsize()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return offsetup - queueup.size();
	}
	void basictipmetadata(nlohmann::json & identifiers, uint64_t & uploaded, uint64_t & total)
	{
		std::lock_guard<std::mutex> lock(mutex);
		identifiers = skystream::identifiers();
		total = offsetup;
		uploaded = total - queueup.size();
	}

	void append(std::vector<uint8_t> && data)
	{
		std::lock_guard<std::mutex> lock(mutex);
		queueup.insert(queueup.end(), data.begin(), data.end());
		moredataup.notify_all();
	}

	std::vector<uint8_t> read(double offset)
	{
		std::unique_lock<std::mutex> lock(mutex);
		reading.notify_all();
		offsetdown = offset;
		queuedown.clear();
		moredatadown.wait(lock, [&]() {
			return !pumping || queuedown.size() != 0;
		});
		std::vector<uint8_t> data = std::move(queuedown);
		return data;
	}
	void doneread()
	{
		std::lock_guard<std::mutex> lock(mutex);
		offsetdown = -1;
		queuedown.clear();
	}

	std::mutex mutex;
	std::condition_variable uploaded; // notified when the size increases

private:
	std::condition_variable reading;
	void start()
	{
		std::lock_guard<std::mutex> lock(mutex);
		offsetup = span("bytes").second;
		offsetdown = -1;
		threadup = std::thread(&BufferedSkystream::pumpup, this);
		threadup.detach();
		threaddown = std::thread(&BufferedSkystream::pumpdown, this);
		threaddown.detach();
	}
	void pumpup()
	{
		while ("pumploop") {
			std::vector<uint8_t> data;

			{
				std::unique_lock<std::mutex> lock(mutex);
				moredataup.wait(lock, [&]() {
					return !pumping || queueup.size() != 0;
				});
				if (!pumping && queueup.size() == 0) {
					uploaded.notify_all();
					return;
				}
				data = std::move(queueup);
			}
			if (data.size()) {
				write(data, "bytes", offsetup);
				offsetup += data.size();
				{
					std::lock_guard<std::mutex> lock(mutex);
					uploaded.notify_all();
				}
			}
		}
	}

	void pumpdown()
	{
		ssize_t offset = -1;
		while ("pumploop") {
			std::vector<uint8_t> data;
			{
				std::unique_lock<std::mutex> lock(mutex);
				if (offset == -1) {
					reading.wait(lock);
				}
				offset = offsetdown;
				if  (!pumping) {
					moredatadown.notify_all();
					return;
				}
			}
			if (offset != -1) {
				auto data = skystream::read("bytes", offset);
				if (data.size()) {
					std::lock_guard<std::mutex> lock(mutex);
					offset += data.size();
					queuedown.insert(queuedown.end(), data.begin(), data.end());
					offsetdown = offset;
					moredatadown.notify_all();
				} else {
					std::lock_guard<std::mutex> lock(mutex);
					offsetdown = offset = -1;
				}
			} 
		}
	}

	bool pumping = true;
	std::thread threadup;
	std::thread threaddown;
	std::condition_variable moredataup;
	std::condition_variable moredatadown;
	std::vector<uint8_t> queueup;
	std::vector<uint8_t> queuedown;
	size_t offsetup;
	size_t offsetdown;
};
*/

class BufferedSkystream : public skystream
{
public:
	using skystream::skystream;
	BufferedSkystream(sia::portalpool & portalpool, std::mutex & groupmutex, std::condition_variable & reading)
	:skystream(portalpool),groupmutex(groupmutex),reading(reading) {start();}
	BufferedSkystream(nlohmann::json identifiers, sia::portalpool & portalpool, std::mutex & groupmutex, std::condition_variable & reading)
	:skystream(identifiers, portalpool),groupmutex(groupmutex),reading(reading) {start();}

	BufferedSkystream(BufferedSkystream const &) = default;
	BufferedSkystream(BufferedSkystream &&) = default;

	~BufferedSkystream()
	{
		if (backlogs()) {
			throw std::runtime_error("not flushed");
		}
	}

	uint64_t size()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return offsetup;
	}
	uint64_t backlog()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return queueup.size();
	}
	uint64_t uploadedsize()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return offsetup - queueup.size();
	}
	std::pair<uint64_t,uint64_t> uploaded_and_total()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return {offsetup - queueup.size(), offsetup};
	}
	void basictipmetadata(nlohmann::json & identifiers, uint64_t & uploaded, uint64_t & total)
	{
		std::lock_guard<std::mutex> lock(mutex);
		identifiers = skystream::identifiers();
		total = offsetup;
		uploaded = total - queueup.size();
	}

	void queue_local_up(std::vector<uint8_t> && data, size_t maxsize = 0)
	{
		size_t uploaded = 0;
		while (uploaded < data.size()) {
			size_t toupload = data.size() - uploaded;
			{
				std::unique_lock<std::mutex> lock(mutex);
				if (maxsize > 0 && queueup.size() >= maxsize) {
					uploaded.wait(lock, [&]() {
						return !pumping || queueup.size() < maxsize;
					});
				}
				if (!pumping) {
					lock.unlock();
					moredataup.notify_all();
					return;
				}
				if (queueup.size() + toupload > maxsize) {
					toupload = maxsize - queueup.size() ;
				}
				queueup.insert(queueup.end(), data.begin() + uploaded, data.begin() + uploaded + toupload);
			}
			moredataup.notify_all();
			uploaded += toupload;
		}
	}

	size_t queue_net_down()
	{
		ssize_t offset = -1;
		while ("pumploop") {
			std::vector<uint8_t> data;
			{
				{
					std::unique_lock<std::mutex> lock(mutex);
					offset = offsetdown;
				}
				if (offset == -1) {
					std::unique_lock<std::mutex> grouplock(groupmutex);
					reading.wait(grouplock);
				}
				{
					std::unique_lock<std::mutex> lock(mutex);
					if  (!pumping) {
						lock.unlock();
						moredatadown.notify_all();
						return;
					}
				}
			}
			if (offset != -1) {
				auto data = skystream::read("bytes", offset);
				offset += data.size();
				{
					std::lock_guard<std::mutex> lock(mutex);
					queuedown.insert(queuedown.end(), data.begin(), data.end());
					offsetdown = offset;
				}
				moredatadown.notify_all();
				return data.size();
			} 
		}
	}

	std::mutex read_mutex;
	std::vector<uint8_t> xfer_local_down(uint64_t offset)
	{
		reading.notify_all();
		std::lock_guard<std::mutex> read_lock(read_mutex);
		std::unique_lock<std::mutex> lock(mutex);
		offsetdown = offset;
		queuedown.clear();
		moredatadown.wait(lock, [&]() {
			return !pumping || queuedown.size() != 0;
		});
		std::vector<uint8_t> data = std::move(queuedown);
		return data;
	}
	void done_local_down()
	{
		std::lock_guard<std::mutex> lock(mutex);
		offsetdown = -1;
		queuedown.clear();
	}

	void xfer_net_up()
	{
		while ("pumploop") {
			std::vector<uint8_t> data;

			{
				std::unique_lock<std::mutex> lock(mutex);
				moredataup.wait(lock, [&]() {
					return !pumping || queueup.size() != 0;
				});
				if (!pumping && queueup.size() == 0) {
					lock.unlock();
					uploaded.notify_all();
					return;
				}
				data = std::move(queueup);
			}
			if (data.size()) {
				write(data, "bytes", offsetup);
				{
					std::lock_guard<std::mutex> lock(mutex);
					offsetup += data.size();
				}
				uploaded.notify_all();
				return;
			}
		}
	}

	std::mutex & groupmutex; 
	std::condition_variable & reading; // notified when read is requested

	std::mutex mutex;
	std::condition_variable uploaded; // notified when write queue is emptied
	std::condition_variable moredataup; // notified when write queue lengthens
	std::condition_variable moredatadown; // notified when read queue lengthens

private:
	void stop()
	{
		{
			std::lock_guard<std::mutex> lock(mutex);
			if (!pumping) {
				return;
			}
			pumping = false;
		}
	}
	void start()
	{
		std::lock_guard<std::mutex> lock(mutex);
		offsetup = span("bytes").second;
		offsetdown = -1;
	}
	bool pumping = true;
	std::vector<uint8_t> queueup;
	std::vector<uint8_t> queuedown;
	size_t offsetup;
	size_t offsetdown;
};

class BufferedSkystreams
{
public:
	BufferedSkystream()
	{
		activedown = 0;
		threaddown = std::thread(&BufferedSkystreams::pumpdown, this);
		threaddown.detach();
		threadup = std::thread(&BufferedSkystream::pumpup, this);
		threadup.detach();
	}
	
	void add(nlohmann::json identifiers, sia::portalpooly & portalpool)
	{
		std::lock_guard<std::mutex> lock(mutex);
		streams.emplace_back(new BufferedSkystream(identifiers, portalpool);
	}

	~BufferedSkystream()
	{
		shutdown();
	}

	void shutdown()
	{
		{
			std::lock_guard<std::mutex> lock(mutex);
			if (!pumping) {
				return;
			}
			pumping = false;
		}
		threadup.join();
		threaddown.join();
	}

	std::pair<uint64_t,uint64_t> uploaded_and_total()
	{
		std::lock_guard<std::mutex> lock(mutex);
		uint64_t maxsize = 0;
		int64_t minsize = -1;
		for (auto stream : streams) {
			auto bounds = stream.uploaded_and_total();
			if (bounds.second > maxsize) {
				maxsize = bounds.second;
			}
			if (minsize == -1 || bounds.first < minsize) {
				minsize = bounds.first;
			}
		}
		return {minsize,maxsize};
	}

	void queue_local_up(size_t stream, std::vector<uint8_t> && data, size_t maxsize = 0)
	{
		std::lock_guard<std::mutex> lock(mutex);
		streams[stream]->queue_local_up(data, maxsize);
	}

	std::vector<uint8_t> xfer_local_down(size_t stream, uint64_t offset)
	{
		BufferedSkystream * streamptr;
		{
			std::unique_lock<std::mutex> lock(mutex);
			streamptr = streams[stream];
		}
		return streamptr->xfer_local_down(offset);
	}
	void done_local_down()
	{
		std::lock_guard<std::mutex> lock(mutex);
		if (activedown != 0) {
			activedown->done_local_down();
			activedown = 0;
		}
	}

private:

	// download needs step-through
	void pumpdown()
	{
		while ("pumploop") {
			BufferedSkystream * stream;
			{
				std::unique_lock<std::mutex> lock(mutex);
				while (activedown == 0 && pumping) {
					reading.wait(lock);
				}
				if  (!pumping) {
					return;
				}
				stream = activedown;
			}
			stream->queue_net_down();
		}
	}

	void pumpup()
	{
		while ("pumploop") {
			BufferedSkystream * streamptr;
			uint64_t maxbacklog = 0;
			{
				std::unique_lock<std::mutex> lock(mutex);
				for (auto stream: streams) {
					uint64_t backlog = stream->backlog();
					if (backlog > maxbacklog) {
						maxbacklog = backlog;
						streamptr = stream;
					}
				}
			}
			if (maxbacklog == 0) {
				std::unique_lock<std::mutex> lock(mutex);
				wrote.wait(lock);
				continue;
			}
			// does this work?
			// 	spawn a thread that calls the upload function
			// a little, but leaves race unless we can pass worker in.

			// simpler: make a new pump queue.
			// each has a thread.
			// LEFT OFF HERE
			stream->xfer_net_up();
		}
	}

	sia::portalpool portalpool;
	std::vector<std::unique_ptr<BufferedSkystream>> streams;


	bool pumping = true;
	std::mutex mutex;

	std::condition_variable reading; // notified when read is requested
	BufferedSkystream * activedown;
	std::thread threaddown;

	std::condition_variable wrote; // notified when data is written
	std::thread threadup;

	std::condition_variable moredataup;
	std::condition_variable moredatadown;
	std::vector<uint8_t> queueup;
	std::vector<uint8_t> queuedown;
	size_t offsetup;
	size_t offsetdown;
};

class Plotfile
{
public:
	Plotfile(uint64_t account)
	: account(account), metastream(portalpool)
	{
		std::cerr << "Readying scoop pumps ..." << std::endl;
		while (scoops.size() < sizeof(nonce::scoops) / sizeof(nonce::scoop)) {
			metadata["scoopstreams"][scoops.size()] = nullptr;
			scoops.emplace_back(new BufferedSkystream(portalpool));
			std::cerr << scoops.size() << "/" << sizeof(nonce::scoops) / sizeof(nonce::scoop) << "\r" << std::flush;
		}
		start();
	}
	Plotfile(uint64_t account, nlohmann::json identifiers)
	: account(account), metastream(identifiers, portalpool), _identifiers(identifiers)
	{
		auto data = metastream.read("index", metastream.span("index").second);
		std::string str(data.begin(), data.end());
		metadata = nlohmann::json::parse(str);
		std::cerr << "Found metadata document. " << std::endl;
		std::cerr << "Readying scoop pumps ..." << std::endl;
		for (auto & identifiers :metadata["scoopstreams"]) {
			scoops.emplace_back(new BufferedSkystream(portalpool));
			std::cerr << scoops.size() << "/" << sizeof(nonce::scoops) / sizeof(nonce::scoop) << "\r" << std::flush;
		}
		start();
	}

	int64_t filename_to_noncecount(std::string name)
	{
		auto pos1 = name.find_first_of('_');
		auto pos2 = name.find_first_of('_', pos1);
		if (pos2 == std::string::npos || pos1 == std::string::npos) {
			return -1;
		}
		try {
			uint64_t account = std::stoull(name.substr(0, pos1));
			uint64_t startingnonce = std::stoull(name.substr(pos1+1, pos2-pos1 - 1));
			uint64_t noncecount = std::stoull(name.substr(pos2+1,name.size()-pos2-1));
			if (startingnonce != 0 || account != this->account) {
				return -1;
			}
			if (noncecount > this->noncecount()) {
				return -1;
			}
			return noncecount;
		} catch(...) {
			return -1;
		}
	}

	std::string filename()
	{
		return std::to_string(account) + "_0_" + std::to_string(noncecount());
	}

	nlohmann::json identifiers()
	{
		std::lock_guard<std::mutex> guard(mutex);
		return _identifiers;
	}

	uint64_t noncecount()
	{
		std::lock_guard<std::mutex> guard(mutex);
		return depth;
	}

	size_t readscoops(uint8_t * buf, uint64_t noncecount, size_t offset, size_t size)
	{
		constexpr uint64_t scoopcount = sizeof(nonce::scoops) / sizeof(nonce::scoop);
		// noncecount shows total filesize
		// scoop id is within offset
		uint64_t scoopssize = noncecount * sizeof(nonce) / scoopcount;
		uint64_t scoopsindex = offset / scoopssize;
		offset -= scoopsindex * scoopssize;
		if (scoopsindex != lastscoopread) {
			scoops[lastscoopread]->doneread();
			lastscoopread = scoopsindex;
		}
		auto data = scoops[scoopsindex]->read(offset);
		if (data.size() > size) {
			data.resize(size);
		}
		std::copy(data.begin(), data.end(), buf);
		return data.size();
	}

	void shutdown()
	{
		if (stoppedcount() == 0) {
			incrementstoppedcount();
			scoopsthread.join();
			metadatathread.join();
		}
	}

	uint64_t const account;

private:
	void start()
	{
		scoopsthread = std::thread(&Plotfile::sendplot, this);
		metadatathread = std::thread(&Plotfile::scribeplot, this);
		lastscoopread = 0;
	}
	void sendplot()
	{
		std::cerr << "Beginning plot generation thread ..." << std::endl;
		uint64_t depthup;
		{
			std::lock_guard<std::mutex> guard(mutex);
			depthup = this->depth;
		}
		nonce plotbit;
		while (stoppedcount() == 0) {
			// generate 1 nonce, and append all scoops to stream
			create_plot(account, depthup, 2, (uint8_t*)&plotbit, 0);
			
			// convert to scoops
			for (size_t index = 0; index < sizeof(plotbit.scoops) / sizeof(nonce::scoop); ++ index) {
				auto & scoop = plotbit.scoops[index];
				std::vector<uint8_t> data;
				data.resize(sizeof(nonce::scoop));
				std::copy((char*)&scoop,(char*)(&scoop+1),data.data());
				assert(scoops[index]->size() == depthup * data.size());
				// scoops bounds should all have the right index
				scoops[index]->append(std::move(data));
			}
			++ depthup;
		}
		// wait for all scoops to send
		for (auto & scoop : scoops) {
			scoop->shutdown();
		}
		incrementstoppedcount();
	}
	void scribeplot()
	{
		std::cerr << "Beginning plot consolidation thread ..." << std::endl;
		int64_t lastminimum = depth;
		while (stoppedcount() < 2) {
			int64_t minimum = -1;
			size_t minimumindex;
			for (size_t index = 0; index < scoops.size(); ++ index) {
				nlohmann::json identifiers;
				uint64_t uploaded, total;
				scoops[index]->basictipmetadata(identifiers, uploaded, total);
				metadata["scoopstreams"][index] = identifiers;
				if (uploaded < minimum || minimum == -1) {
					minimum = uploaded;
					minimumindex = index;
				}
			}
			if (minimum > lastminimum) {
				std::cerr << "Stored new noncecount of " << minimum << "." << std::endl;
				lastminimum = minimum;
				std::vector<uint8_t> data;
				{
					std::lock_guard<std::mutex> guard(mutex);
					depth = minimum;
					std::string datastr = metadata.dump();
					data.insert(data.end(), datastr.begin(), datastr.end());
				}
				metastream.write(data, "bytes", metastream.span("bytes").second);
				{
					std::lock_guard<std::mutex> guard(mutex);
					_identifiers = metastream.identifiers();
				}
			} else {
				std::unique_lock<std::mutex> lock(scoops[minimumindex]->mutex);
				scoops[minimumindex]->uploaded.wait(lock);
			}
		}
	}
	// skystream:
	// .get(json identifiers) // returns a std::vector<uint8_t> for identifires["skylink"]
	// .identifiers() // get identifiers for stream
	// .block_span(std::string span, double offset) // return a pair of bounds around offset
	// .span(string span) // return a pair of bounds for span
	// .write(vector data, string span, double offset) // write to stream, offset should be end of span
	// .read(string span, double offset, string flow = "real") // read from stream, returns vector
	// spans are "bytes", "time", "index"
	// so we could write to nonces or scoops
	sia::portalpool portalpool;
	skystream metastream;
	nlohmann::json metadata;
	std::vector<std::unique_ptr<BufferedSkystream>> scoops;

	std::thread metadatathread;
	std::thread scoopsthread;
	ssize_t lastscoopread;

	std::mutex mutex;
	int _stoppedcount;
	uint64_t depth;
	nlohmann::json _identifiers;
	int stoppedcount()
	{
		std::lock_guard<std::mutex> guard(mutex);
		return _stoppedcount;
	}
	void incrementstoppedcount()
	{
		std::lock_guard<std::mutex> guard(mutex);
		++ _stoppedcount;
	}
	
};

#define FUSE_USE_VERSION 34
#include "Fusepp/Fuse.cpp"


#include <fstream>
#include <sstream>
#include <cstdio> // for rename
#include <cstring>  // for strerror, handling rename's return
class PlotFS : public Fusepp::Fuse<PlotFS>
{
public:
	PlotFS(std::string configfilename)
	{
		PlotFS::configfilename = configfilename;
		uint64_t account = std::stoull(configfilename);
		std::cerr << "Opening config file " << configfilename << " ..." << std::endl;
		std::ifstream configfile(configfilename);
		if (configfile.is_open()) {
			std::ostringstream configstrm;
			configstrm << configfile.rdbuf();
			std::string configstr = configstrm.str();

			std::cerr << "Resuming plotting for account id " << account << " ..." << std::endl;
			plotfile = new Plotfile(account,nlohmann::json::parse(configstr));
			lastnoncecount = plotfile->noncecount();
		} else {
			std::cerr << " ... failed.  Will write file after starting to plot." << std::endl;
			std::cerr << "Initiating plotting for account id " << account << " ..." << std::endl;
			plotfile = new Plotfile(account);
			updateconfig();
		}
	}
	~PlotFS()
	{
		plotfile->shutdown();
		updateconfig();
		delete plotfile;
	}
	static void updateconfig()
	{
		auto noncecount = plotfile->noncecount();
		if (noncecount == lastnoncecount) {
			return;
		}
		std::cerr << "Writing " << configfilename << " with " << noncecount << " nonces ..." << std::endl;
		lastnoncecount = noncecount;
		std::istringstream configstrm(plotfile->identifiers().dump());
		std::string tempfile = configfilename + "_update";
		std::ofstream configfile(tempfile);
		configfile << configstrm.rdbuf();
		configfile.close();
		int result = std::rename(tempfile.c_str(), configfilename.c_str());
		if (result != 0) {
			throw std::runtime_error(strerror(result));
		}
	}
	static int getattr(const char *path, struct stat *stbuf, struct fuse_file_info *)
	{
		memset(stbuf, 0, sizeof(struct stat));
		if (path[0] == '/' && path[1] == 0) {
			stbuf->st_mode = S_IFDIR | 0755;
			stbuf->st_nlink = 2;
			return 0;
		}
		if (path[0] != '/') {
			return -ENOENT;
		}
		auto noncecount = plotfile->filename_to_noncecount(path + 1);
		if (noncecount == -1) {
			return -ENOENT;
		}
		stbuf->st_mode = S_IFREG | 0444;
		stbuf->st_nlink = 1;
		stbuf->st_size = noncecount * sizeof(nonce);
		return 0;
	}
	static int readdir(const char *path, void*buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi, enum fuse_readdir_flags)
	{
		if (path[0] != '/' || path[1] != 0) {
			return -ENOENT;
		}
	
		filler(buf, ".", NULL, 0, FUSE_FILL_DIR_PLUS);
		filler(buf, "..", NULL, 0, FUSE_FILL_DIR_PLUS);
		std::string filename = plotfile->filename();
		filler(buf, filename.c_str(), NULL, 0, FUSE_FILL_DIR_PLUS);
		updateconfig();
	
		return 0;
	}
	static int open(const char *path, struct fuse_file_info *fi)
	{
		if ((fi->flags & 3) != O_RDONLY) {
			return -EACCES;
		}

		auto noncecount = plotfile->filename_to_noncecount(path + 1);
		if (noncecount == -1) {
			return -ENOENT;
		}
		updateconfig();
	
		return 0;
	}
	static int read(const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
	{
		auto noncecount = plotfile->filename_to_noncecount(path + 1);
		if (noncecount == -1) {
			return -ENOENT;
		}
	
		return plotfile->readscoops((uint8_t*)buf, noncecount, offset, size);
	}
	// PlotFS is hacky because Fusepp is incomplete
	static Plotfile * plotfile;
	static uint64_t lastnoncecount;
	static std::string configfilename;
};
Plotfile * PlotFS::plotfile;
uint64_t PlotFS::lastnoncecount;
std::string PlotFS::configfilename;

int main(int argc, char **argv)
{
	if (argc<2) {
		std::cout << "Provide <accountnum>.json as first argument." << std::endl;
		return -1;
	}
	PlotFS plotfs(argv[1]);
	plotfs.run(argc-1, argv+1);
}
